version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  groups:
      osu-related:
        patterns:
          - "ppy.osu.*"
      dotnet-tools:
        patterns:
          - "cake.tool"
          - "jetbrains.resharper.globaltools"
          - "nvika"
          - "codefilesanity"
