name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore osu.Framework.Microphone.Tests
    - name: Build with .NET
      run: dotnet build osu.Framework.Microphone.Tests --no-restore --configuration Release
    - name: Unit Tests
      run: dotnet test osu.Framework.Microphone.Tests --no-build --no-restore --configuration Release